"""``./manage.py export_targeted_keywords [--out path]`` — dump the keywords the
content pipeline has already TARGETED, so a fresh ``/seo-clustering`` run can drop them
from the pool before clustering (``seo_ingest.py keywords --exclude <file>``).

The dedup spine: every ``blog.ContentPlan`` row from the keyword-clustering path carries
its demand evidence in ``keywords`` (``[{"keyword": str, "volume": int}, ...]``). A
keyword is **targeted** once its row has progressed past mere planning:

* it has a non-empty ``brief`` (the brief stage committed a per-article plan for it), OR
* it is ``produced`` (a ``Post`` or glossary ``Tag`` exists for the row), OR
* its ``status`` is ``generating`` / ``drafted`` / ``published`` (in or past production).

``planned`` / ``reconciled`` rows are still just queued — their keywords stay in the pool.
``rejected`` / ``merged`` rows are not targeted either (rejected freed the keyword; a merged
row's demand lives on its surviving row), so they are excluded from the export.

Output is one keyword per line (lowercased, de-duplicated, sorted), with a ``#``-comment
header carrying the counts — exactly the shape ``seo_ingest.py keywords --exclude`` reads.
Run inside the web container so it reads the live roadmap.
"""

from __future__ import annotations

from django.core.management.base import BaseCommand

from keel_content import host

ContentPlan = host.content_plan_model()

# A row at or past these statuses is committed work — its keywords are targeted.
_PRODUCTION_STATUSES = frozenset(
    (
        ContentPlan.Status.GENERATING,
        ContentPlan.Status.DRAFTED,
        ContentPlan.Status.PUBLISHED,
    )
)
# These rows never contribute targeted keywords (freed / superseded demand).
_EXCLUDED_STATUSES = frozenset(
    (
        ContentPlan.Status.REJECTED,
        ContentPlan.Status.MERGED,
    )
)


def _is_targeted(row) -> bool:
    """True when the row's keywords should be excluded from a fresh clustering run."""
    if row.status in _EXCLUDED_STATUSES:
        return False
    if row.status in _PRODUCTION_STATUSES:
        return True
    if row.is_produced:  # produced_post or produced_term set
        return True
    return bool(row.brief)  # non-empty brief dict = briefed


class Command(BaseCommand):
    help = (
        "Export keywords already targeted (briefed or produced) by the content "
        "pipeline, for /seo-clustering to exclude from a fresh run."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--out",
            default="",
            help="Write to this path instead of stdout (one keyword per line).",
        )

    def handle(self, *args, **opts):
        # Only rows that could match — skip the freed/superseded ones in the query.
        rows = ContentPlan.objects.exclude(status__in=list(_EXCLUDED_STATUSES)).only(
            "status", "brief", "keywords", "produced_post", "produced_term"
        )
        seen: set[str] = set()
        n_rows = 0
        for row in rows.iterator():
            if not _is_targeted(row):
                continue
            n_rows += 1
            for kw in row.keywords or []:
                text = str((kw or {}).get("keyword", "")).strip().lower()
                if text:
                    seen.add(text)

        keywords = sorted(seen)
        header = (
            f"# targeted keywords (briefed or produced) — {len(keywords)} unique "
            f"from {n_rows} ContentPlan row(s)\n"
            "# generated by manage.py export_targeted_keywords; feed to "
            "seo_ingest.py keywords --exclude <this file>\n"
        )
        body = "\n".join(keywords)
        text = header + body + ("\n" if body else "")

        if opts["out"]:
            with open(opts["out"], "w", encoding="utf-8") as fh:
                fh.write(text)
            self.stderr.write(
                f"Wrote {len(keywords)} targeted keyword(s) from {n_rows} row(s) -> {opts['out']}"
            )
        else:
            self.stdout.write(text)
